schema_version = "1.0.0"

id = "DreamScape_generator"
version = "1.0.0"
name = "Dreamscape Generator"
tagline = "Generate Patterns, reveal patterns, dissolve patterns"
maintainer = "Vaishnav"
website = "https://blendermarket.com/products/neon-dreamscapes"
type = "add-on"
blender_version_min = "4.2.0"
license = ["SPDX:GPL-3.0-or-later"]
